spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java-short-message-service
    username: postgres
    password: nHcEkDMab9jgCQZJ
  jpa:
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
security:
  jwt:
    secret: "1EABB71CBCCCA98154079DD31ADD619F941CC6D935EBD8DCDEDDBC631AD9A18141F8C08D58CFEAB104D43AED52BFADFC867F92BDAD8EAE9E3CFD9E74971653D2"
    expiration: 86400000
  public:
    path: "/public/**"

pagination:
  default-size: 5
