spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/java_short_message_service
    username: postgres
    password: root
  jpa:
    database: postgresql
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
security:
  jwt:
    secret: "message-sender-java-jwt"
    expiration: 86400000
  public:
    path: "/public/**"

pagination:
  default-size: 5
