spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/messageSenderDb
    username: root
    password: ifsul2017
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
